import faster_than_requests as req
from glom import glom
import json

returnData = req.get2json_pretty("https://randomuser.me/api/")
returnData = json.loads(returnData)
print("Gathered Data From Server")

#   Adding data in to a variables
lastName = glom(returnData, 'results.0.name.first')
firstName = glom(returnData, 'results.0.name.last')
gender = glom(returnData, 'results.0.gender')
address = str(glom(returnData, 'results.0.location.street.number')) + " " + glom(returnData, 'results.0.location.street.name')
city = glom(returnData, 'results.0.location.city')
state = glom(returnData, 'results.0.location.state')
country = glom(returnData, 'results.0.location.country')
latitude = glom(returnData, 'results.0.location.coordinates.latitude')
longitude = glom(returnData, 'results.0.location.coordinates.longitude')
postalcode = str(glom(returnData, 'results.0.location.postcode'))
timezone = glom(returnData, 'results.0.location.timezone.offset') + " " + glom(returnData, 'results.0.location.timezone.description')
email = glom(returnData, 'results.0.email')
dob = glom(returnData, 'results.0.dob.date')
age = str(glom(returnData, 'results.0.dob.age'))
phone = str(glom(returnData, 'results.0.phone'))
cell = str(glom(returnData, 'results.0.cell'))

#   Generating File Name
personName = firstName + " " + lastName
# print(returnData)


f = open(personName, "w+")
f.write("THIS FILE IS GENERATED BY FAKE PERSON GENERATOR\n\n")
f.write("First Name : " + firstName + "\n")
f.write("Last Name : " + lastName + "\n")
f.write("Gender : " + gender + "\n\n")
f.write("Address : " + address + "\n")
f.write("City : " + city + "\n")
f.write("State : " + state + "\n")
f.write("Country : " + country + "\n")
f.write("Latitude : " + latitude + "\n")
f.write("Longitude : " + longitude + "\n")
f.write("Postal Code : " + postalcode + "\n")
f.write("Timezone : " + timezone + "\n\n")
f.write("Email : " + email + "\n")
f.write("Birthday : " + dob + "\n")
f.write("Age : " + age + "\n\n")
f.write("Telephone : " + phone + "\n")
f.write("Cell Phone : " + cell + "\n")

print("Processing Done : " + personName + ".txt")
