import faster_than_requests as req
import tkinter as tk
from glom import glom
import json


def request_data():
    xdarr = ['First Name', 'Last Name', 'Gender', 'Address', 'City', 'State', 'Country', 'Latitude', 'Longitude','Postal Code', 'Time Zone', 'Email', 'Birthday', 'Age', 'Telephone', 'Cell Phone']
    returnData = req.get2json_pretty("https://randomuser.me/api/")
    returnData = json.loads(returnData)

    # Adding JSON data into a array using generator
    arr = []
    for value in formatplus(returnData):
        arr.append(value)

    # Formating array with given keys using zip
    formatarr = list(zip(xdarr, arr))

    # Calling writedata function for save the file
    writedata(formatarr)


def writedata(array):
    # use person name as text file name
    personName = array[0][1] + " " + array[1][1] + ".txt"
    
    # Creating text file using context manager
    with open(personName, 'w+') as file:
        file.write("THIS FILE IS GENERATED BY FAKE PERSON GENERATOR\n")

        # writing array information to text file using for loop
        for key, value in array:
            file.write(f'{key} : {value}\n')


# Accessing JSON data using glom and add all returned data into a array
def formatplus(returnData):

    # Using glom to access data in the JSON object.
    # Using simple generator to return the data 
    yield glom(returnData, 'results.0.name.first')
    yield glom(returnData, 'results.0.name.last')
    yield glom(returnData, 'results.0.gender')
    yield str(glom(returnData, 'results.0.location.street.number')) + " " + glom(returnData, 'results.0.location.street.name')
    yield glom(returnData, 'results.0.location.city')
    yield glom(returnData, 'results.0.location.state')
    yield glom(returnData, 'results.0.location.country')
    yield glom(returnData, 'results.0.location.coordinates.latitude')
    yield glom(returnData, 'results.0.location.coordinates.longitude')
    yield str(glom(returnData, 'results.0.location.postcode'))
    yield glom(returnData, 'results.0.location.timezone.offset') + " " + glom(returnData, 'results.0.location.timezone.description')
    yield glom(returnData, 'results.0.email')
    yield glom(returnData, 'results.0.dob.date')
    yield str(glom(returnData, 'results.0.dob.age'))
    yield str(glom(returnData, 'results.0.phone'))
    yield str(glom(returnData, 'results.0.cell'))


# Created GUI Window with Tkinter
root = tk.Tk()
root.title("Fake Person Generator")     

canvas = tk.Canvas(root, height=300, width=400)
canvas.pack()

# Adding a background image to a root
background_image = tk.PhotoImage(file='src/background.png')
background_label = tk.Label(root, image=background_image)
background_label.place(relwidth=1, relheight=1)


# Created button with command included
button = tk.Button(root, text="Generate Random Person", font=40, command=request_data)
button.place(relx=0.2, rely=0.3, relheight=0.10, relwidth=0.6)


root.mainloop()
