import faster_than_requests as req
import tkinter as tk
import json


def request_data():
    # xdarr = ['First Name', 'Last Name', 'Gender', 'Address', 'City', 'State', 'Country', 'Latitude', 'Longitude','Postal Code', 'Time Zone', 'Email', 'Birthday', 'Age', 'Telephone', 'Cell Phone']
    returnData = req.get2json_pretty("https://randomuser.me/api/")
    returnData = dict(json.loads(returnData))
    results = returnData['results'][0]
    rec(results)
    writedata(arr)

# this array belong to rec
arr = []


def rec(dicto):
    if isinstance(dicto, dict) is False:
        pass
    keys = list(dicto.keys())

    for k in keys:
        if isinstance(dicto[k], (list, dict)):
            rec(dicto[k])
        else:
            # print(f'{k} value is {dicto[k]}')
            val = str(k) + " ::: " + str(dicto[k])
            arr.append(val)
            # print(arr)


def writedata(array):
    personName = str(array[2].split(':::')[1]) + "_" + str(array[3].split(':::')[1]) + ".txt"
    # print(str)
    with open(personName, 'w+') as file:
        file.write("THIS FILE IS GENERATED BY FAKE PERSON GENERATOR\n")

        # writing array information to text file using for loop
        for value in array:
            file.write(f'{value}\n')


# Created GUI Window with Tkinter
root = tk.Tk()
root.title("Fake Person Generator")     

canvas = tk.Canvas(root, height=300, width=400)
canvas.pack()

# Adding a background image to a root
background_image = tk.PhotoImage(file='src/background.png')
background_label = tk.Label(root, image=background_image)
background_label.place(relwidth=1, relheight=1)


# Created button with command included
button = tk.Button(root, text="Generate Random Person", font=40, command=request_data)
button.place(relx=0.2, rely=0.3, relheight=0.10, relwidth=0.6)


root.mainloop()