import faster_than_requests as req
import json


def request_data():
    # xdarr = ['First Name', 'Last Name', 'Gender', 'Address', 'City', 'State', 'Country', 'Latitude', 'Longitude','Postal Code', 'Time Zone', 'Email', 'Birthday', 'Age', 'Telephone', 'Cell Phone']
    returnData = req.get2json_pretty("https://randomuser.me/api/")
    returnData = dict(json.loads(returnData))
    results = returnData['results'][0]
    rec(results)


def rec(dicto):
    arr[]
    if isinstance(dicto, dict) is False:
        pass
    keys = list(dicto.keys())

    for k in keys:
        if isinstance(dicto[k], (list, dict)):
            rec(dicto[k])
        else:
            print(f'{k} value is {dicto[k]}')


def writedata(array):
    personName = array[0][1] + " " + array[1][1] + ".txt"
    
    with open(personName, 'w+') as file:
        file.write("THIS FILE IS GENERATED BY FAKE PERSON GENERATOR\n")

        # writing array information to text file using for loop
        for key, value in array:
            file.write(f'{key} : {value}\n')

request_data()